[package]
name = "mx-human-codec-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2.10", features = ["js"] }
wee_alloc = "0.4.5"
wasm-bindgen = "0.2.89"
serde_json = "1.0.108"
console_error_panic_hook = "0.1.7"

multiversx-sc-codec-human-readable = { git = "https://github.com/multiversx/mx-sdk-rs.git", rev = "db17a176fc5d43388ba8099ca38282fb00bb856f" }
multiversx-sc-meta-lib = { git = "https://github.com/multiversx/mx-sdk-rs.git", rev = "db17a176fc5d43388ba8099ca38282fb00bb856f" }
multiversx-sc = { git = "https://github.com/multiversx/mx-sdk-rs.git", rev = "db17a176fc5d43388ba8099ca38282fb00bb856f" }